name: CI

on:
  push:
    #branches: [ "main" ]
    branches: [ "add_build_versions" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: image-build-and-push
    strategy:
      matrix:
          PYTHON_VERSION: [py37, py38, py39]
          RAY_VERSION: [1.11.0, 1.12.0, 1.13.0]
          TORCH_VERSION: [1.12.0+cu116, 1.11.0+cu115]
    steps:
      # docker login source https://github.com/docker/login-action
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_REGISTRY_USER }}
          password: ${{ secrets.GH_REGISTRY_PUSH_TOKEN }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build and push
        env:
          RAY_VERSION: ${{ matrix.RAY_VERSION }}-${{matrix.PYTHON_VESRION}}-gpu
          TORCH_VERSION: ${{ matrix.TORCH_VERSION }}
        run: echo "RAY_VERSION ${RAY_VERSION}"
        #run: ./buildAndPush.sh
