name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: image-build-and-push
    strategy:
      matrix:
        include:
          - RAY_VERSION: 1.11.0-gpu
            TORCH_VERSION: 1.11.0+cu115
          - RAY_VERSION: 1.11.0-gpu
            TORCH_VERSION: 1.12.0+cu116
          - RAY_VERSION: 1.13.0-gpu
            TORCH_VERSION: 1.11.0+cu115
          - RAY_VERSION: 1.13.0-gpu
            TORCH_VERSION: 1.12.0+cu116
    steps:
      # docker login source https://github.com/docker/login-action
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_REGISTRY_USER }}
          password: ${{ secrets.GH_REGISTRY_PUSH_TOKEN }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build and push
        env:
          RAY_VERSION: ${{ matrix.RAY_VERSION }}
          TORCH_VERSION: ${{ matrix.TORCH_VERSION }}
        run: ./buildAndPush.sh
